AWSTemplateFormatVersion: "2010-09-09"
Description: A managed policy allowing deployments to an S3 bucket, using aws s3 sync API
Parameters:
  Project:
    AllowedPattern: '[a-z0-9]+'
    Description: Project name (alphanumeric)
    Type: String
  Environment:
    Description: Environment
    Type: String
  S3Bucket:
    Description: Name of bucket, NOT arn
    Type: String
Outputs:
  PolicyArn:
    Value: !Ref S3DeployManagedPolicy
Resources:
# #### S3 deploy policy
# Allowing listing the bucket, deleting objects, as well as creating objects and object ACLs
# ####
  S3DeployManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: "/"
      PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:DeleteObject
                - s3:PutObject
                - s3:PutObjectAcl
              Resource:
                - !Sub "arn:aws:s3:::${S3Bucket}"
                - !Sub "arn:aws:s3:::${S3Bucket}/*"