AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudFront Distribution for a static website hosted on S3. By passing in CloudFrontAliases and
  CloudFrontAcmCertificateArn you can use a custom HTTPS hostname for the distribution rather than the default
  which is in the format https://xxxx.cloudfront.net

Parameters:

  Project:
    AllowedPattern: '[a-z0-9]+'
    Description: Project name (alphanumeric)
    Type: String

  Environment:
    Description: Environment
    Type: String

  S3WebsiteURL:
    Description: http:// URL for the s3 website to distribute
    Type: String

  CloudFrontAliases:
    Description: A comma separated list of CNAME aliases to set up for the CloudFront Distribution
    Type: String
    Default: 'NONE'

  CloudFrontAcmCertificateArn:
    Description: Arn for a custom ACM HTTPS certificate. Use this in combination with CloudFrontAliases.
    Type: String
    Default: 'NONE'

  ViewerProtocolPolicy:
    Description: Controls what HTTP protocol viewers use to access CloudFront
    Type: String
    Default: redirect-to-https

Conditions:

  UseCustomCloudFrontAliases: !Not [ !Equals [ !Ref CloudFrontAliases, 'NONE' ] ]

  UseCustomCloudFrontAcmCertificate: !Not [ !Equals [ !Ref CloudFrontAcmCertificateArn, 'NONE' ] ]

Outputs:

  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref S3WebsiteCloudFrontDistribution

  DistributionDomainName:
    Description: CloudFront Distribution domain / URL
    Value: !GetAtt S3WebsiteCloudFrontDistribution.DomainName

Resources:

# #### S3 Website CloudFront Distribution
# A CF Distribution to a S3 Static Website origin.
# We can use cloudfront default domain or pass CloudFrontAliases and CloudFrontAcmCertificateArn to use custom domain,
# with HTTPS enabled only on this domain
# Additionally we are only using North America + Europe edge locations for cost
# ####
  S3WebsiteCloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases: !If
          - UseCustomCloudFrontAliases
          - !Split [ ',', !Ref CloudFrontAliases ]
          - !Ref AWS::NoValue
        Comment: "CF Distribution for ${Project}-${Environment} web app"
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          TargetOriginId: S3WebsiteOrigin
          ViewerProtocolPolicy: !Ref ViewerProtocolPolicy
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
            # Everything after http://
            DomainName: !Select [2, !Split ["/", !Ref S3WebsiteURL]]
            Id: S3WebsiteOrigin
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: !If
            - UseCustomCloudFrontAcmCertificate
            - !Ref AWS::NoValue
            - true
          AcmCertificateArn: !If
            - UseCustomCloudFrontAcmCertificate
            - !Ref CloudFrontAcmCertificateArn
            - !Ref AWS::NoValue
          SslSupportMethod: !If
            - UseCustomCloudFrontAcmCertificate
            - sni-only
            - !Ref AWS::NoValue