name: web-admin deployment

# develop -> dev
# qa -> qa
# main -> uat
# prod -> prod/live

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
      - issue/*
      - bug/*
      - hotfix/*
      - develop
      - qa
      - main
      - prod
  pull_request:
    branches:
      - feature/*
      - issue/*
      - bug/*
      - hotfix/*

# Cancel any redundent workflows of same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT: carolinegirvan-webadmin
  CI_REGISTRY_IMAGE: hedgehoglab-client/carolinegirvan-web
  CI_ENVIRONMENT_NAME: DEV
  CI_SLACK_CHANNEL: ${{ secrets.CI_SLACK_CHANNEL }}
  CI_SLACK_WEBHOOK_URL: ${{ secrets.CI_SLACK_WEBHOOK_URL }}
  CI_JOB_ID: ${{ github.run_id }}
  CI_PIPELINE_ID: ${{ github.run_id }}

permissions:
  contents: read
  packages: write

jobs:
  lint_test_build_release:
    runs-on: [internal-linux]
    container:
      image: ghcr.io/hedgehoglab-engineering/docker-aws:latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: |
          export CI_BRANCH_SLUG=$(echo ${GITHUB_REF#refs/heads/} | sed -e 's/[^A-Za-z0-9._-]/_/g')
          export CI_PIPELINE_ID=${{ github.run_id }}
          docker pull ${CI_REGISTRY_IMAGE}:${CI_BRANCH_SLUG} || true
          docker build --build-arg CI=${CI} --cache-from ${CI_REGISTRY_IMAGE}:${CI_BRANCH_SLUG} -t ${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID} -t ${CI_REGISTRY_IMAGE}:${CI_BRANCH_SLUG} .

      - name: Dev deploy
        run: |
          export CI_COMMIT_REF_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed -e 's/[^A-Za-z0-9._-]/_/g')
          ./ci deploy && ./ci deploy_success_slack || { ./ci deploy_failure_slack; exit 1; }
        env:
          CI_ENVIRONMENT_NAME: DEV
          DEV_REACT_APP_ENV_NAME: ${{ secrets.DEV_REACT_APP_ENV_NAME }}
          DEV_REACT_APP_SERVER: ${{ secrets.DEV_REACT_APP_SERVER }}
          DEV_CI_DEPLOY_ACCESS_KEY_ID: ${{ secrets.DEV_CI_DEPLOY_ACCESS_KEY_ID }}
          DEV_CI_DEPLOY_SECRET_ACCESS_KEY: ${{ secrets.DEV_CI_DEPLOY_SECRET_ACCESS_KEY }}
          DEV_CI_DEPLOY_REGION: ${{ secrets.DEV_CI_DEPLOY_REGION }}
          DEV_CI_DEPLOY_BUCKET: ${{ secrets.DEV_CI_DEPLOY_BUCKET }}
          DEV_CI_CF_DISTRIBUTION: ${{ secrets.DEV_CI_CF_DISTRIBUTION }}

      - name: QA deploy
        if: github.ref == 'refs/heads/qa'
        run: |
          export CI_COMMIT_REF_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed -e 's/[^A-Za-z0-9._-]/_/g')
          ./ci deploy && ./ci deploy_success_slack || { ./ci deploy_failure_slack; exit 1; }
        env:
          CI_ENVIRONMENT_NAME: QA
          QA_REACT_APP_ENV_NAME: ${{ secrets.QA_REACT_APP_ENV_NAME }}
          QA_REACT_APP_SERVER: ${{ secrets.QA_REACT_APP_SERVER }}
          QA_CI_DEPLOY_ACCESS_KEY_ID: ${{ secrets.QA_CI_DEPLOY_ACCESS_KEY_ID }}
          QA_CI_DEPLOY_SECRET_ACCESS_KEY: ${{ secrets.QA_CI_DEPLOY_SECRET_ACCESS_KEY }}
          QA_CI_DEPLOY_REGION: ${{ secrets.QA_CI_DEPLOY_REGION }}
          QA_CI_DEPLOY_BUCKET: ${{ secrets.QA_CI_DEPLOY_BUCKET }}
          QA_CI_CF_DISTRIBUTION: ${{ secrets.QA_CI_CF_DISTRIBUTION }}

      - name: UAT deploy
        if: github.ref == 'refs/heads/main'
        run: |
          export CI_COMMIT_REF_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed -e 's/[^A-Za-z0-9._-]/_/g')
          ./ci deploy && ./ci deploy_success_slack || { ./ci deploy_failure_slack; exit 1; }
        env:
          CI_ENVIRONMENT_NAME: UAT
          UAT_REACT_APP_ENV_NAME: ${{ secrets.UAT_REACT_APP_ENV_NAME }}
          UAT_REACT_APP_SERVER: ${{ secrets.UAT_REACT_APP_SERVER }}
          UAT_CI_DEPLOY_ACCESS_KEY_ID: ${{ secrets.UAT_CI_DEPLOY_ACCESS_KEY_ID }}
          UAT_CI_DEPLOY_SECRET_ACCESS_KEY: ${{ secrets.UAT_CI_DEPLOY_SECRET_ACCESS_KEY }}
          UAT_CI_DEPLOY_REGION: ${{ secrets.UAT_CI_DEPLOY_REGION }}
          UAT_CI_DEPLOY_BUCKET: ${{ secrets.UAT_CI_DEPLOY_BUCKET }}
          UAT_CI_CF_DISTRIBUTION: ${{ secrets.UAT_CI_CF_DISTRIBUTION }}

      - name: PROD deploy
        if: github.ref == 'refs/heads/prod'
        run: |
          export CI_COMMIT_REF_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed -e 's/[^A-Za-z0-9._-]/_/g')
          ./ci deploy && ./ci deploy_success_slack || { ./ci deploy_failure_slack; exit 1; }
        env:
          CI_ENVIRONMENT_NAME: PROD
          PROD_REACT_APP_ENV_NAME: ${{ secrets.PROD_REACT_APP_ENV_NAME }}
          PROD_REACT_APP_SERVER: ${{ secrets.PROD_REACT_APP_SERVER }}
          PROD_CI_DEPLOY_ACCESS_KEY_ID: ${{ secrets.PROD_CI_DEPLOY_ACCESS_KEY_ID }}
          PROD_CI_DEPLOY_SECRET_ACCESS_KEY: ${{ secrets.PROD_CI_DEPLOY_SECRET_ACCESS_KEY }}
          PROD_CI_DEPLOY_REGION: ${{ secrets.PROD_CI_DEPLOY_REGION }}
          PROD_CI_DEPLOY_BUCKET: ${{ secrets.PROD_CI_DEPLOY_BUCKET }}
          PROD_CI_CF_DISTRIBUTION: ${{ secrets.PROD_CI_CF_DISTRIBUTION }}
